title: Feeds
email: namilin@icloud.com
logo_url: https://img.yzcdn.cn/upload_files/2017/05/03/149378919182472097.jpg
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll

theme: the-plain
plugins:
  - jekyll-feed
